services:
  # Backend API service
  - type: web
    name: molar-mass-calculator-api
    runtime: docker
    repo: https://github.com/AnnaNajafiH/ChemCal.git
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: molar-mass-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: DOCKER_ENV
        value: "true"

databases:
  - name: molar-mass-db
    plan: free
    type: mysql
    databaseName: molar_mass_db
    user: molar_user
    ipAllowList: []  # Only allow internal connections
