services:
  # Backend API service
  - type: web
    name: molar-mass-calculator-api
    runtime: docker
    repo: https://github.com/AnnaNajafiH/ChemCal.git
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: molar-mass-db
          property: connectionString
      - key: MYSQL_DATABASE
        value: molar_mass_db
      - key: MYSQL_USER
        value: molar_user
      - key: MYSQL_PASSWORD
        sync: false

  # Frontend web service using static site hosting
  - type: web
    name: molar-mass-calculator-frontend
    runtime: static
    repo: https://github.com/AnnaNajafiH/ChemCal.git
    branch: main
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: molar-mass-calculator-api
          type: web
          property: url

databases:
  - name: molar-mass-db
    plan: free
    type: mysql
    databaseName: molar_mass_db
    user: molar_user
    ipAllowList: []  # Only allow internal connections
